services:
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=hexagonal

  db-tst:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=hexagonal-tst

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"   
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus

  loki:
    image: grafana/loki:2.9.1
    ports:
      - "3100:3100"
    volumes:
      - ./src/infra/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"  
      - "4318:4318"   
      - "9600:9600"   
    volumes:
      - ./src/infra/otel-collector-config.yaml:/etc/otelcol/config.yaml
    command:
      - "--config=/etc/otelcol/config.yaml"
    depends_on:
      - loki
      - prometheus
